//! Wheel Strategy Engine
//!
//! The Wheel Strategy is a systematic options income approach:
//!
//! 1. **Cash-Secured Put (CSP)**: Sell an OTM put on a stock you want to own.
//!    Collect premium. If assigned, you buy 100 shares at the strike.
//!
//! 2. **Covered Call (CC)**: After assignment, sell an OTM call against the
//!    shares. Collect premium. If called away, you sell the shares at the
//!    strike and restart with a new CSP.
//!
//! This module evaluates the user's inventory and the available options chain
//! to surface the best CSP and CC candidates ranked by quality criteria.

use serde::{Deserialize, Serialize};

use crate::models::{OptionsChain, OptionsContract, OptionType, StockHolding};

// ── Quality thresholds (configurable in a real app) ─────────────────────────

/// Minimum annualised return on capital to surface a recommendation.
const MIN_ANNUALISED_ROC: f64 = 12.0; // percent

/// Preferred DTE range for new positions.
const MIN_DTE: u32 = 1;
const MAX_DTE: u32 = 45;

/// Target delta range for CSPs (absolute value).
const CSP_DELTA_MIN: f64 = 0.20;
const CSP_DELTA_MAX: f64 = 0.35;

/// Target delta range for CCs (absolute value).
const CC_DELTA_MIN: f64 = 0.20;
const CC_DELTA_MAX: f64 = 0.35;

/// Minimum open interest to ensure liquidity.
const MIN_OPEN_INTEREST: u64 = 100;

// ── Output types ─────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "snake_case")]
pub enum WheelLeg {
    /// Sell a cash-secured put – no existing shares needed.
    CashSecuredPut,
    /// Sell a covered call against existing shares.
    CoveredCall,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WheelRecommendation {
    pub ticker: String,
    pub leg: WheelLeg,
    pub contract: OptionsContract,
    /// Annualised return on capital (percent).
    pub annualised_roc: f64,
    /// Qualitative quality score (0–100).
    pub quality_score: f64,
    /// Human-readable rationale generated by the strategy engine.
    pub rationale: String,
    /// Number of shares the user holds for this ticker.
    pub shares_held: u32,
    /// How many contracts to sell at this strike/expiry (≥1).
    /// For covered calls this reflects the tiered allocation across strikes.
    /// For CSPs this is always 1 (each qualifying strike listed separately).
    pub contracts_allocated: u32,
}

// ── Engine ────────────────────────────────────────────────────────────────────

/// Evaluate options chains against the user's inventory and return ranked
/// wheel strategy recommendations.
///
/// Rules:
/// - If the user holds ≥ 100 shares of a ticker → surface CC candidates.
/// - For every ticker in the chains (regardless of inventory) → surface CSP
///   candidates (the user may want to acquire more shares).
pub fn evaluate_wheel(
    inventory: &[StockHolding],
    chains: &[OptionsChain],
    available_cash: f64,
) -> Vec<WheelRecommendation> {
    let mut recommendations: Vec<WheelRecommendation> = Vec::new();

    // ── Phase 1: Covered Calls (per-ticker — requires holdings) ──────────────
    for chain in chains {
        let holding = inventory
            .iter()
            .find(|h| h.ticker.to_uppercase() == chain.ticker.to_uppercase());

        let shares_held = holding.map(|h| h.shares).unwrap_or(0);

        if shares_held >= 100 {
            let lots = (shares_held / 100) as usize;

            let mut cc_qualified: Vec<&OptionsContract> = chain
                .contracts
                .iter()
                .filter(|c| {
                    c.option_type == OptionType::Call
                        && c.dte >= MIN_DTE
                        && c.dte <= MAX_DTE
                        && c.delta.abs() >= CC_DELTA_MIN
                        && c.delta.abs() <= CC_DELTA_MAX
                        && c.open_interest >= MIN_OPEN_INTEREST
                        && c.strike > chain.underlying_price
                        && c.cc_return_on_capital() >= MIN_ANNUALISED_ROC
                })
                .collect();

            cc_qualified.sort_by(|a, b| {
                let sa = compute_quality_score(a, a.cc_return_on_capital());
                let sb = compute_quality_score(b, b.cc_return_on_capital());
                sb.partial_cmp(&sa).unwrap_or(std::cmp::Ordering::Equal)
            });

            let tiers = select_cc_tiers(&cc_qualified, chain.underlying_price, lots);
            let allocations = allocate_lots(lots, tiers.len());

            for (contract, n_contracts) in tiers.iter().zip(allocations.iter()) {
                let roc = contract.cc_return_on_capital();
                let score = compute_quality_score(contract, roc);
                let rationale =
                    format_cc_rationale(contract, roc, shares_held, *n_contracts, lots);
                recommendations.push(WheelRecommendation {
                    ticker: chain.ticker.clone(),
                    leg: WheelLeg::CoveredCall,
                    contract: (*contract).clone(),
                    annualised_roc: roc,
                    quality_score: score,
                    rationale,
                    shares_held,
                    contracts_allocated: *n_contracts as u32,
                });
            }
        }
    }

    // ── Phase 2: Cash-Secured Puts — global cross-ticker optimization ──────────
    //
    // Goals:
    //  1. Every ticker in the chains gets at least one CSP candidate (small/illiquid
    //     stocks fall back to relaxed filters rather than disappearing entirely).
    //  2. Candidates are ranked by total strategy premium = floor(cash/(strike×100))
    //     × mid × 100.  This correctly values 100 contracts of a $10 stock vs
    //     2 contracts of a $400 stock — whichever collects more absolute premium wins.
    //  3. Multi-stage greedy allocation: Stage 1 deploys as much cash as possible
    //     into the best ticker; Stage 2 deploys remaining cash into the next best;
    //     Stage 3 handles any further remainder.  This is the "allocate until nothing
    //     profitable remains" logic the user asked for.
    //  4. Alternatives are shown for every ticker so the user can compare.

    struct CspEntry {
        ticker: String,
        shares_held: u32,
        holding_note: String,
        contract: OptionsContract,
    }

    // Total premium achievable given full available cash (used for ranking).
    let compute_tp = |c: &OptionsContract| -> f64 {
        let n = if available_cash.is_finite() && available_cash > 0.0 {
            (available_cash / (c.strike * 100.0)).floor().max(1.0)
        } else { 1.0 };
        n * c.mid_price() * 100.0
    };

    let mut all_csp: Vec<CspEntry> = Vec::new();

    for chain in chains {
        let holding = inventory.iter()
            .find(|h| h.ticker.to_uppercase() == chain.ticker.to_uppercase());
        let shares_held = holding.map(|h| h.shares).unwrap_or(0);

        // If the user holds ≥ 100 shares, they should sell covered calls — not CSPs.
        if shares_held >= 100 {
            continue;
        }

        let holding_note = match holding {
            Some(h) if h.shares > 0 =>
                format!("You hold {} shares; assignment brings you toward a covered call.", h.shares),
            _ => "No existing position — assignment opens a new wheel cycle.".to_string(),
        };

        // ── Strict filter pass ──────────────────────────────────────────────
        let strict: Vec<OptionsContract> = chain.contracts.iter()
            .filter(|c| {
                c.option_type == OptionType::Put
                    && c.dte >= MIN_DTE && c.dte <= MAX_DTE
                    && c.delta.abs() >= CSP_DELTA_MIN && c.delta.abs() <= CSP_DELTA_MAX
                    && c.open_interest >= MIN_OPEN_INTEREST
                    && c.strike < chain.underlying_price
                    && c.csp_return_on_capital() >= MIN_ANNUALISED_ROC
            })
            .cloned()
            .collect();

        if !strict.is_empty() {
            tracing::debug!(ticker = %chain.ticker, count = strict.len(), "CSP strict pass");
            for c in strict {
                all_csp.push(CspEntry {
                    ticker: chain.ticker.clone(),
                    shares_held,
                    holding_note: holding_note.clone(),
                    contract: c,
                });
            }
        } else {
            // ── Relaxed fallback ────────────────────────────────────────────
            // Ensures every ticker is represented.  Widens delta range, lowers OI
            // floor, and lowers ROC bar — critical for small/illiquid stocks where
            // standard thresholds eliminate all candidates.
            tracing::debug!(ticker = %chain.ticker, "CSP strict pass = 0, trying relaxed filters");
            let relaxed: Vec<OptionsContract> = chain.contracts.iter()
                .filter(|c| {
                    c.option_type == OptionType::Put
                        && c.dte >= MIN_DTE && c.dte <= MAX_DTE
                        && c.delta.abs() >= 0.10 && c.delta.abs() <= 0.50
                        && c.open_interest >= 5
                        && c.strike < chain.underlying_price
                        && c.csp_return_on_capital() >= 5.0
                })
                .cloned()
                .collect();

            tracing::debug!(ticker = %chain.ticker, count = relaxed.len(), "CSP relaxed pass");

            // From relaxed candidates, keep only the one with the best total premium.
            if let Some(best) = relaxed.into_iter().max_by(|a, b|
                compute_tp(a).partial_cmp(&compute_tp(b)).unwrap_or(std::cmp::Ordering::Equal)
            ) {
                all_csp.push(CspEntry {
                    ticker: chain.ticker.clone(),
                    shares_held,
                    holding_note: holding_note.clone(),
                    contract: best,
                });
            }
        }
    }

    if !all_csp.is_empty() {
        // ── Per-ticker best contract ──────────────────────────────────────────
        // For each ticker identify the index of its contract with the highest
        // total premium.  Used as the input for stage allocation.
        let mut ticker_best_idx: std::collections::HashMap<String, usize> =
            std::collections::HashMap::new();
        let mut ticker_order: Vec<String> = Vec::new(); // insertion order = discovery order

        for (i, entry) in all_csp.iter().enumerate() {
            let tp = compute_tp(&entry.contract);
            let prev_tp = ticker_best_idx
                .get(&entry.ticker)
                .map(|&pi| compute_tp(&all_csp[pi].contract))
                .unwrap_or(f64::NEG_INFINITY);

            if tp > prev_tp {
                if !ticker_best_idx.contains_key(&entry.ticker) {
                    ticker_order.push(entry.ticker.clone());
                }
                ticker_best_idx.insert(entry.ticker.clone(), i);
            }
        }

        // Sort tickers by their best total premium (descending).
        ticker_order.sort_by(|a, b| {
            let ta = compute_tp(&all_csp[ticker_best_idx[a]].contract);
            let tb = compute_tp(&all_csp[ticker_best_idx[b]].contract);
            tb.partial_cmp(&ta).unwrap_or(std::cmp::Ordering::Equal)
        });

        // ── Multi-stage greedy allocation ─────────────────────────────────────
        // Stage 1: best ticker → deploy as many contracts as available_cash allows.
        // Stage 2: with remaining cash → next best ticker.
        // Stage 3: further remainder → third ticker (if any).
        // Stops when cash is exhausted or no more tickers remain.
        let mut stage_cash = available_cash;
        // (index into all_csp, n_contracts, stage label)
        let mut stages: Vec<(usize, u32, String)> = Vec::new();

        for (stage_pos, ticker) in ticker_order.iter().enumerate() {
            if stage_pos >= 3 { break; }
            let idx = ticker_best_idx[ticker];
            let capital = all_csp[idx].contract.strike * 100.0;
            if capital <= 0.0 { continue; }

            let n: u32 = if stage_cash.is_infinite() {
                1
            } else {
                let n = (stage_cash / capital).floor() as u32;
                if n == 0 { continue; } // can't fit even one contract — skip this ticker
                n
            };

            if !stage_cash.is_infinite() {
                stage_cash -= n as f64 * capital;
            }

            let label = match (stage_pos, ticker_order.len()) {
                (_, 1) => "optimal allocation".to_string(),
                (0, _) => format!(
                    "primary: deploy ${:.0} ({} contracts)",
                    n as f64 * capital, n),
                (1, _) => format!(
                    "secondary: ${:.0} remaining → {} contract{}",
                    n as f64 * capital, n, if n == 1 { "" } else { "s" }),
                _ => format!(
                    "tertiary: ${:.0} remaining → {} contract{}",
                    n as f64 * capital, n, if n == 1 { "" } else { "s" }),
            };

            stages.push((idx, n, label));
        }

        // ── Rationale builder ─────────────────────────────────────────────────
        let make_rationale = |entry: &CspEntry, label: Option<&str>, n: u32| -> String {
            let prefix = label.map(|l| format!("[{}] ", l)).unwrap_or_default();
            let sp = n as f64 * entry.contract.mid_price() * 100.0;
            let col = n as f64 * entry.contract.strike * 100.0;
            let qty_note = if n > 1 {
                format!(" {} contracts: total premium ${:.0}, collateral ${:.0}.", n, sp, col)
            } else { String::new() };
            format!(
                "{}Sell ${:.2} put, {} DTE (Δ{:.2}, IV {:.0}%). \
                 Mid ${:.2}/contract. Ann ROC {:.1}%. OTM {:.1}%.{} {}",
                prefix,
                entry.contract.strike,
                entry.contract.dte,
                entry.contract.delta,
                entry.contract.implied_volatility * 100.0,
                entry.contract.mid_price(),
                entry.contract.csp_return_on_capital(),
                (entry.contract.underlying_price - entry.contract.strike)
                    / entry.contract.underlying_price * 100.0,
                qty_note,
                entry.holding_note,
            )
        };

        // ── Emit primary stage allocations ────────────────────────────────────
        for (pos, (idx, n, label)) in stages.iter().enumerate() {
            let entry = &all_csp[*idx];
            let roc = entry.contract.csp_return_on_capital();
            let score = compute_quality_score(&entry.contract, roc)
                * if pos == 0 { 1.0 } else { 0.97_f64.powi(pos as i32) };
            recommendations.push(WheelRecommendation {
                ticker: entry.ticker.clone(),
                leg: WheelLeg::CashSecuredPut,
                contract: entry.contract.clone(),
                annualised_roc: roc,
                quality_score: score,
                rationale: make_rationale(entry, Some(label.as_str()), *n),
                shares_held: entry.shares_held,
                contracts_allocated: *n,
            });
        }

        // ── Emit alternatives ─────────────────────────────────────────────────
        // For tickers already in stages: show alternative strikes/DTEs.
        // For tickers not in stages: show as "compare" so user can evaluate.
        let stage_keys: std::collections::HashSet<(String, u64, u32)> = stages.iter()
            .map(|(idx, _, _)| {
                let e = &all_csp[*idx];
                (e.ticker.clone(), (e.contract.strike * 100.0).round() as u64, e.contract.dte)
            })
            .collect();
        let stage_tickers: std::collections::HashSet<&str> = stages.iter()
            .map(|(idx, _, _)| all_csp[*idx].ticker.as_str())
            .collect();

        let mut alt_sorted_indices: Vec<usize> = (0..all_csp.len()).collect();
        alt_sorted_indices.sort_by(|&a, &b| {
            compute_tp(&all_csp[b].contract)
                .partial_cmp(&compute_tp(&all_csp[a].contract))
                .unwrap_or(std::cmp::Ordering::Equal)
        });

        let mut alt_per_ticker: std::collections::HashMap<String, usize> =
            std::collections::HashMap::new();
        let max_alt_per_ticker = 2usize;
        let max_alt_total = 8usize;
        let mut alt_emitted = 0usize;

        for idx in alt_sorted_indices {
            if alt_emitted >= max_alt_total { break; }
            let entry = &all_csp[idx];
            let key = (
                entry.ticker.clone(),
                (entry.contract.strike * 100.0).round() as u64,
                entry.contract.dte,
            );
            if stage_keys.contains(&key) { continue; }

            let count = alt_per_ticker.entry(entry.ticker.clone()).or_insert(0);
            if *count >= max_alt_per_ticker { continue; }

            let roc = entry.contract.csp_return_on_capital();
            let score = compute_quality_score(&entry.contract, roc) * 0.88;
            let n = if available_cash.is_finite() && available_cash > 0.0 {
                (available_cash / (entry.contract.strike * 100.0)).floor().max(1.0) as u32
            } else { 1 };
            let label = if stage_tickers.contains(entry.ticker.as_str()) {
                "alt strike/DTE"
            } else {
                "compare: alternative ticker"
            };

            recommendations.push(WheelRecommendation {
                ticker: entry.ticker.clone(),
                leg: WheelLeg::CashSecuredPut,
                contract: entry.contract.clone(),
                annualised_roc: roc,
                quality_score: score,
                rationale: make_rationale(entry, Some(label), n),
                shares_held: entry.shares_held,
                contracts_allocated: n,
            });
            *count += 1;
            alt_emitted += 1;
        }
    }

    // Sort: CCs and CSPs together by quality score.
    recommendations.sort_by(|a, b| {
        b.quality_score
            .partial_cmp(&a.quality_score)
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    recommendations
}

// ── CC tiered strike selection ────────────────────────────────────────────────

/// Select up to 3 strikes for covered-call tiering.
///
/// Strategy:
/// - **1 lot**: best single strike (max quality).
/// - **2 lots**: best quality + one more conservative (higher) strike.
/// - **≥3 lots**: up to 3 strikes – moderate (best quality), conservative
///   (higher strike, more upside room), and, when ≥5 lots, aggressive
///   (lower/higher premium strike).  Strikes must differ by at least 1 % of
///   underlying to count as a separate tier.
fn select_cc_tiers<'a>(
    sorted_by_quality: &[&'a OptionsContract],
    underlying: f64,
    lots: usize,
) -> Vec<&'a OptionsContract> {
    let min_strike_gap = (underlying * 0.01).max(1.0);
    let max_tiers = if lots >= 5 { 3 } else if lots >= 2 { 2 } else { 1 };

    let mut tiers: Vec<&OptionsContract> = Vec::new();

    for &contract in sorted_by_quality {
        if tiers.len() >= max_tiers {
            break;
        }
        // Ensure this strike is sufficiently different from all chosen strikes.
        let distinct = tiers
            .iter()
            .all(|t| (t.strike - contract.strike).abs() >= min_strike_gap);
        if distinct {
            tiers.push(contract);
        }
    }

    // Sort tiers from highest strike (conservative) to lowest (aggressive)
    // so the rationale labels map intuitively.
    tiers.sort_by(|a, b| {
        b.strike
            .partial_cmp(&a.strike)
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    tiers
}

/// Distribute `lots` contracts across `n_tiers` tiers using a 40 / 40 / 20
/// split (or 60 / 40 for 2 tiers, or 100 % for 1 tier).
/// Each tier always gets at least 1 contract.
fn allocate_lots(lots: usize, n_tiers: usize) -> Vec<usize> {
    if n_tiers == 0 || lots == 0 {
        return vec![];
    }
    if n_tiers == 1 {
        return vec![lots];
    }
    if n_tiers == 2 {
        let t1 = (lots as f64 * 0.60).round() as usize;
        let t1 = t1.max(1).min(lots - 1);
        return vec![t1, lots - t1];
    }
    // 3 tiers: conservative 40 %, moderate 40 %, aggressive 20 %
    let t1 = (lots as f64 * 0.40).round() as usize;
    let t1 = t1.max(1).min(lots - 2); // leave room for the other two
    let t3 = (lots as f64 * 0.20).round() as usize;
    let t3 = t3.max(1).min(lots - t1 - 1);
    let t2 = lots - t1 - t3;
    vec![t1, t2, t3]
}

// ── Scoring ───────────────────────────────────────────────────────────────────

/// Composite quality score weighing ROC, IV, delta centrality, and liquidity.
fn compute_quality_score(contract: &OptionsContract, annualised_roc: f64) -> f64 {
    // Reward higher ROC (capped at 50 pts).
    let roc_score = (annualised_roc / 60.0 * 50.0).min(50.0);

    // Reward delta near the middle of the target range (0–20 pts).
    let target_delta = 0.275_f64; // midpoint of 0.20–0.35
    let delta_deviation = (contract.delta.abs() - target_delta).abs();
    let delta_score = ((0.075 - delta_deviation) / 0.075 * 20.0).max(0.0);

    // Reward higher open interest for liquidity (0–20 pts).
    let oi_score = (contract.open_interest as f64 / 5_000.0 * 20.0).min(20.0);

    // Reward IV between 25–60 % (sweet spot for premium selling) (0–10 pts).
    let iv_score = if contract.implied_volatility >= 0.25
        && contract.implied_volatility <= 0.60
    {
        10.0
    } else if contract.implied_volatility > 0.60 {
        5.0 // high IV but elevated risk
    } else {
        2.0 // low IV, poor premium
    };

    roc_score + delta_score + oi_score + iv_score
}

// ── Rationale formatters ──────────────────────────────────────────────────────

fn format_cc_rationale(c: &OptionsContract, roc: f64, shares: u32, contracts: usize, total_lots: usize) -> String {
    let tier_label = if total_lots >= 3 {
        // Label by delta position: lower delta = more conservative (higher strike)
        if c.delta.abs() <= 0.24 {
            "Conservative tranche"
        } else if c.delta.abs() >= 0.29 {
            "Aggressive tranche"
        } else {
            "Moderate tranche"
        }
    } else {
        "Position"
    };

    let contracts_note = if total_lots >= 2 {
        format!(
            "{contracts} of {total_lots} contract(s) ({tier_label}). "
        )
    } else {
        String::new()
    };

    format!(
        "{contracts_note}Sell the ${:.0} call expiring in {} DTE \
         (delta {:.2}, IV {:.0}%) against {shares} shares. \
         Mid premium: ${:.2}/contract. Annualised ROC: {:.1}%. \
         Strike is {:.1}% OTM, {}.",
        c.strike,
        c.dte,
        c.delta,
        c.implied_volatility * 100.0,
        c.mid_price(),
        roc,
        ((c.strike - c.underlying_price) / c.underlying_price) * 100.0,
        if c.delta.abs() <= 0.24 {
            "allowing more room for the stock to rise before assignment"
        } else if c.delta.abs() >= 0.29 {
            "capturing higher premium with tighter upside cap"
        } else {
            "balancing premium income with upside participation"
        }
    )
}
