//! Wheel Strategy Engine
//!
//! The Wheel Strategy is a systematic options income approach:
//!
//! 1. **Cash-Secured Put (CSP)**: Sell an OTM put on a stock you want to own.
//!    Collect premium. If assigned, you buy 100 shares at the strike.
//!
//! 2. **Covered Call (CC)**: After assignment, sell an OTM call against the
//!    shares. Collect premium. If called away, you sell the shares at the
//!    strike and restart with a new CSP.
//!
//! This module evaluates the user's inventory and the available options chain
//! to surface the best CSP and CC candidates ranked by quality criteria.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

use crate::models::{EarningsCalendar, OptionsChain, OptionsContract, OptionType, StockHolding};

/// Warn when a contract's DTE spans past an earnings date within this window.
const EARNINGS_WARNING_DAYS: i64 = 14;

// ── Quality thresholds (defaults, overridable via FilterParams) ──────────────

/// Minimum annualised return on capital to surface a recommendation.
const DEFAULT_MIN_ANNUALISED_ROC: f64 = 12.0; // percent

/// Target delta range for CSPs (absolute value).
const DEFAULT_CSP_DELTA_MIN: f64 = 0.20;
const DEFAULT_CSP_DELTA_MAX: f64 = 0.35;

/// Target delta range for CCs (absolute value).
const DEFAULT_CC_DELTA_MIN: f64 = 0.20;
const DEFAULT_CC_DELTA_MAX: f64 = 0.35;

/// Minimum open interest to ensure liquidity.
const DEFAULT_MIN_OPEN_INTEREST: u64 = 100;

/// Filter parameters that can be overridden by the caller.
#[derive(Debug, Clone, Default)]
pub struct FilterParams {
    pub min_open_interest: Option<u64>,
    pub cc_delta_min: Option<f64>,
    pub cc_delta_max: Option<f64>,
    pub csp_delta_min: Option<f64>,
    pub csp_delta_max: Option<f64>,
    pub min_annualised_roc: Option<f64>,
    pub max_annualised_roc: Option<f64>,
}

// ── Output types ─────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "snake_case")]
pub enum WheelLeg {
    /// Sell a cash-secured put – no existing shares needed.
    CashSecuredPut,
    /// Sell a covered call against existing shares.
    CoveredCall,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WheelRecommendation {
    pub ticker: String,
    pub leg: WheelLeg,
    pub contract: OptionsContract,
    /// Annualised return on capital (percent).
    pub annualised_roc: f64,
    /// Qualitative quality score (0–100).
    pub quality_score: f64,
    /// Human-readable rationale generated by the strategy engine.
    pub rationale: String,
    /// Number of shares the user holds for this ticker.
    pub shares_held: u32,
    /// How many contracts to sell at this strike/expiry (≥1).
    /// For covered calls this reflects the tiered allocation across strikes.
    /// For CSPs this is always 1 (each qualifying strike listed separately).
    pub contracts_allocated: u32,
    /// True when the contract's DTE spans past a nearby earnings date.
    #[serde(default)]
    pub earnings_warning: bool,
}

// ── Engine ────────────────────────────────────────────────────────────────────

/// Evaluate options chains against the user's inventory and return ranked
/// wheel strategy recommendations.
///
/// Rules:
/// - If the user holds ≥ 100 shares of a ticker → surface CC candidates.
/// - For every ticker in the chains (regardless of inventory) → surface CSP
///   candidates (the user may want to acquire more shares).
pub fn evaluate_wheel(
    inventory: &[StockHolding],
    chains: &[OptionsChain],
    available_cash: f64,
    min_dte: u32,
    max_dte: u32,
    earnings: &[EarningsCalendar],
    filters: &FilterParams,
) -> Vec<WheelRecommendation> {
    let mut recommendations: Vec<WheelRecommendation> = Vec::new();

    // Resolve filter values (use caller overrides or defaults).
    let min_oi = filters.min_open_interest.unwrap_or(DEFAULT_MIN_OPEN_INTEREST);
    let cc_delta_min = filters.cc_delta_min.unwrap_or(DEFAULT_CC_DELTA_MIN);
    let cc_delta_max = filters.cc_delta_max.unwrap_or(DEFAULT_CC_DELTA_MAX);
    let csp_delta_min = filters.csp_delta_min.unwrap_or(DEFAULT_CSP_DELTA_MIN);
    let csp_delta_max = filters.csp_delta_max.unwrap_or(DEFAULT_CSP_DELTA_MAX);
    let min_roc = filters.min_annualised_roc.unwrap_or(DEFAULT_MIN_ANNUALISED_ROC);
    let max_roc = filters.max_annualised_roc.unwrap_or(120.0);
    let earnings_warn_days = EARNINGS_WARNING_DAYS;

    // Build a map of ticker → nearest future earnings (days_until).
    let mut earnings_map: HashMap<String, i64> = HashMap::new();
    for e in earnings {
        if e.days_until >= 0 {
            let key = e.ticker.to_uppercase();
            let existing = earnings_map.get(&key).copied().unwrap_or(i64::MAX);
            if e.days_until < existing {
                earnings_map.insert(key, e.days_until);
            }
        }
    }

    // Returns true when the contract's DTE spans past a nearby earnings date.
    let has_earnings_risk = |ticker: &str, dte: u32| -> bool {
        match earnings_map.get(&ticker.to_uppercase()) {
            Some(&days_until) if days_until <= earnings_warn_days => {
                (dte as i64) > days_until
            }
            _ => false,
        }
    };

    // ── Phase 1: Covered Calls (per-ticker — requires holdings) ──────────────
    for chain in chains {
        let holding = inventory
            .iter()
            .find(|h| h.ticker.to_uppercase() == chain.ticker.to_uppercase());

        let shares_held = holding.map(|h| h.shares).unwrap_or(0);

        if shares_held >= 100 {
            let lots = (shares_held / 100) as usize;

            // ── Strict CC filter pass ────────────────────────────────────────
            let mut cc_qualified: Vec<&OptionsContract> = chain
                .contracts
                .iter()
                .filter(|c| {
                    c.option_type == OptionType::Call
                        && c.dte >= min_dte
                        && c.dte <= max_dte
                        && c.delta.abs() >= cc_delta_min
                        && c.delta.abs() <= cc_delta_max
                        && c.open_interest >= min_oi
                        && c.strike > chain.underlying_price
                        && c.cc_return_on_capital() >= min_roc
                        && c.cc_return_on_capital() <= max_roc
                })
                .collect();

            // ── Relaxed CC fallback ─────────────────────────────────────────
            // Widens delta range, lowers OI floor and ROC bar so every ticker
            // with ≥ 100 shares always gets at least one CC recommendation.
            if cc_qualified.is_empty() {
                tracing::debug!(ticker = %chain.ticker, "CC strict pass = 0, trying relaxed filters");
                cc_qualified = chain
                    .contracts
                    .iter()
                    .filter(|c| {
                        c.option_type == OptionType::Call
                            && c.dte >= min_dte
                            && c.dte <= max_dte
                            && c.delta.abs() >= 0.10
                            && c.delta.abs() <= 0.50
                            && c.open_interest >= 5
                            && c.strike > chain.underlying_price
                            && c.cc_return_on_capital() >= 5.0
                    })
                    .collect();
                tracing::debug!(ticker = %chain.ticker, count = cc_qualified.len(), "CC relaxed pass");
            }

            cc_qualified.sort_by(|a, b| {
                let sa = compute_quality_score(a, a.cc_return_on_capital());
                let sb = compute_quality_score(b, b.cc_return_on_capital());
                sb.partial_cmp(&sa).unwrap_or(std::cmp::Ordering::Equal)
            });

            let tiers = select_cc_tiers(&cc_qualified, chain.underlying_price, lots);
            let allocations = allocate_lots(lots, tiers.len());

            for (contract, n_contracts) in tiers.iter().zip(allocations.iter()) {
                let roc = contract.cc_return_on_capital();
                let score = compute_quality_score(contract, roc);
                let rationale =
                    format_cc_rationale(contract, roc, shares_held, *n_contracts, lots);
                recommendations.push(WheelRecommendation {
                    ticker: chain.ticker.clone(),
                    leg: WheelLeg::CoveredCall,
                    contract: (*contract).clone(),
                    annualised_roc: roc,
                    quality_score: score,
                    rationale,
                    shares_held,
                    contracts_allocated: *n_contracts as u32,
                    earnings_warning: has_earnings_risk(&chain.ticker, contract.dte),
                });
            }
        }
    }

    // ── Phase 2: Cash-Secured Puts — global cross-ticker optimization ──────────
    //
    // Skip entirely when no cash is available — CSPs require collateral.
    if available_cash > 0.0 {
    //
    // Goals:
    //  1. Every ticker in the chains gets at least one CSP candidate (small/illiquid
    //     stocks fall back to relaxed filters rather than disappearing entirely).
    //  2. Candidates are ranked by total strategy premium = floor(cash/(strike×100))
    //     × mid × 100.  This correctly values 100 contracts of a $10 stock vs
    //     2 contracts of a $400 stock — whichever collects more absolute premium wins.
    //  3. Multi-stage greedy allocation: Stage 1 deploys as much cash as possible
    //     into the best ticker; Stage 2 deploys remaining cash into the next best;
    //     Stage 3 handles any further remainder.  This is the "allocate until nothing
    //     profitable remains" logic the user asked for.
    //  4. Alternatives are shown for every ticker so the user can compare.

    struct CspEntry {
        ticker: String,
        shares_held: u32,
        holding_note: String,
        contract: OptionsContract,
    }

    // Total premium achievable given full available cash (used for ranking).
    let compute_tp = |c: &OptionsContract| -> f64 {
        let n = if available_cash.is_finite() && available_cash > 0.0 {
            (available_cash / (c.strike * 100.0)).floor().max(1.0)
        } else { 1.0 };
        n * c.mid_price() * 100.0
    };

    let mut all_csp: Vec<CspEntry> = Vec::new();

    for chain in chains {
        let holding = inventory.iter()
            .find(|h| h.ticker.to_uppercase() == chain.ticker.to_uppercase());
        let shares_held = holding.map(|h| h.shares).unwrap_or(0);

        // If the user holds ≥ 100 shares, they should sell covered calls — not CSPs.
        if shares_held >= 100 {
            continue;
        }

        let holding_note = match holding {
            Some(h) if h.shares > 0 =>
                format!("You hold {} shares; assignment brings you toward a covered call.", h.shares),
            _ => "No existing position — assignment opens a new wheel cycle.".to_string(),
        };

        // ── Strict filter pass ──────────────────────────────────────────────
        let strict: Vec<OptionsContract> = chain.contracts.iter()
            .filter(|c| {
                c.option_type == OptionType::Put
                    && c.dte >= min_dte && c.dte <= max_dte
                    && c.delta.abs() >= csp_delta_min && c.delta.abs() <= csp_delta_max
                    && c.open_interest >= min_oi
                    && c.strike < chain.underlying_price
                    && c.csp_return_on_capital() >= min_roc
                    && c.csp_return_on_capital() <= max_roc
            })
            .cloned()
            .collect();

        if !strict.is_empty() {
            tracing::debug!(ticker = %chain.ticker, count = strict.len(), "CSP strict pass");
            for c in strict {
                all_csp.push(CspEntry {
                    ticker: chain.ticker.clone(),
                    shares_held,
                    holding_note: holding_note.clone(),
                    contract: c,
                });
            }
        } else {
            // ── Relaxed fallback ────────────────────────────────────────────
            // Ensures every ticker is represented.  Widens delta range, lowers OI
            // floor, and lowers ROC bar — critical for small/illiquid stocks where
            // standard thresholds eliminate all candidates.
            tracing::debug!(ticker = %chain.ticker, "CSP strict pass = 0, trying relaxed filters");
            let relaxed: Vec<OptionsContract> = chain.contracts.iter()
                .filter(|c| {
                    c.option_type == OptionType::Put
                        && c.dte >= min_dte && c.dte <= max_dte
                        && c.delta.abs() >= 0.10 && c.delta.abs() <= 0.50
                        && c.open_interest >= 5
                        && c.strike < chain.underlying_price
                        && c.csp_return_on_capital() >= 5.0
                })
                .cloned()
                .collect();

            tracing::debug!(ticker = %chain.ticker, count = relaxed.len(), "CSP relaxed pass");

            // From relaxed candidates, keep only the one with the best total premium.
            if let Some(best) = relaxed.into_iter().max_by(|a, b|
                compute_tp(a).partial_cmp(&compute_tp(b)).unwrap_or(std::cmp::Ordering::Equal)
            ) {
                all_csp.push(CspEntry {
                    ticker: chain.ticker.clone(),
                    shares_held,
                    holding_note: holding_note.clone(),
                    contract: best,
                });
            }
        }
    }

    if !all_csp.is_empty() {
        // ── Per-ticker quality scoring ────────────────────────────────────────
        let csp_quality = |c: &OptionsContract| -> f64 {
            compute_quality_score(c, c.csp_return_on_capital())
        };

        // Group candidates by ticker, sorted by quality descending.
        let mut by_ticker: std::collections::HashMap<String, Vec<usize>> =
            std::collections::HashMap::new();
        for (i, entry) in all_csp.iter().enumerate() {
            by_ticker
                .entry(entry.ticker.clone())
                .or_default()
                .push(i);
        }
        for indices in by_ticker.values_mut() {
            indices.sort_by(|&a, &b| {
                csp_quality(&all_csp[b].contract)
                    .partial_cmp(&csp_quality(&all_csp[a].contract))
                    .unwrap_or(std::cmp::Ordering::Equal)
            });
        }

        // Rank tickers by their best candidate's quality.
        let mut ticker_order: Vec<String> = by_ticker.keys().cloned().collect();
        ticker_order.sort_by(|a, b| {
            let qa = csp_quality(&all_csp[by_ticker[a][0]].contract);
            let qb = csp_quality(&all_csp[by_ticker[b][0]].contract);
            qb.partial_cmp(&qa).unwrap_or(std::cmp::Ordering::Equal)
        });

        // ── Diversified tier selection per ticker ─────────────────────────────
        // Same logic as CC: pick up to 3 (strike, DTE) combos per ticker that
        // differ in strike and/or DTE, with a diversity bonus.
        let min_dte_gap: u32 = 5;

        let select_csp_tiers = |indices: &[usize]| -> Vec<usize> {
            if indices.is_empty() {
                return vec![];
            }
            // First entry is the best quality.
            let first = &all_csp[indices[0]].contract;
            let underlying = first.underlying_price;
            let min_strike_gap = (underlying * 0.01).max(1.0);

            let mut tiers: Vec<usize> = vec![indices[0]];
            let max_tiers = 3usize; // we'll allocate contracts across them later

            while tiers.len() < max_tiers {
                let mut best: Option<(usize, f64)> = None;

                for &idx in indices {
                    let c = &all_csp[idx].contract;

                    // Skip exact duplicates.
                    let is_dup = tiers.iter().any(|&ti| {
                        let t = &all_csp[ti].contract;
                        (t.strike - c.strike).abs() < 0.01 && t.dte == c.dte
                    });
                    if is_dup {
                        continue;
                    }

                    // Must differ in at least one dimension from every chosen tier.
                    let distinct = tiers.iter().all(|&ti| {
                        let t = &all_csp[ti].contract;
                        let diff_strike = (t.strike - c.strike).abs() >= min_strike_gap;
                        let diff_dte = (t.dte as i32 - c.dte as i32).unsigned_abs() >= min_dte_gap;
                        diff_strike || diff_dte
                    });
                    if !distinct {
                        continue;
                    }

                    // Diversity bonus: +5 per dimension that differs from each existing tier.
                    let diversity: f64 = tiers
                        .iter()
                        .map(|&ti| {
                            let t = &all_csp[ti].contract;
                            let s = if (t.strike - c.strike).abs() >= min_strike_gap { 5.0 } else { 0.0 };
                            let d = if (t.dte as i32 - c.dte as i32).unsigned_abs() >= min_dte_gap { 5.0 } else { 0.0 };
                            s + d
                        })
                        .sum();

                    let score = csp_quality(c) + diversity;
                    if best.map_or(true, |(_, bs)| score > bs) {
                        best = Some((idx, score));
                    }
                }

                match best {
                    Some((idx, _)) => tiers.push(idx),
                    None => break,
                }
            }

            // Sort tiers: DTE ascending, then strike descending within each DTE.
            tiers.sort_by(|&a, &b| {
                let ca = &all_csp[a].contract;
                let cb = &all_csp[b].contract;
                ca.dte.cmp(&cb.dte).then_with(|| {
                    cb.strike.partial_cmp(&ca.strike).unwrap_or(std::cmp::Ordering::Equal)
                })
            });

            tiers
        };

        // ── Cash allocation across tickers, then across tiers within each ticker ─
        let mut stage_cash = available_cash;
        // Collect all (tier_idx, n_contracts, ticker, stage_label) to emit.
        let mut all_stages: Vec<(usize, u32, String)> = Vec::new();
        let mut stage_ticker_set: std::collections::HashSet<String> =
            std::collections::HashSet::new();

        for (stage_pos, ticker) in ticker_order.iter().enumerate() {
            if stage_pos >= 3 { break; }
            let indices = &by_ticker[ticker];
            let tiers = select_csp_tiers(indices);
            if tiers.is_empty() { continue; }

            // How many total contracts can we afford at the cheapest tier strike?
            let cheapest_collateral = tiers
                .iter()
                .map(|&ti| all_csp[ti].contract.strike * 100.0)
                .fold(f64::INFINITY, f64::min);
            if cheapest_collateral <= 0.0 { continue; }

            let total_affordable: u32 = if stage_cash.is_infinite() {
                tiers.len() as u32 // at least 1 per tier
            } else {
                let n = (stage_cash / cheapest_collateral).floor() as u32;
                if n == 0 { continue; }
                n
            };

            // Distribute contracts across tiers using allocate_lots.
            let allocs = allocate_lots(total_affordable as usize, tiers.len());

            let mut ticker_cash_used = 0.0_f64;
            for (&tier_idx, &n) in tiers.iter().zip(allocs.iter()) {
                let n = n as u32;
                if n == 0 { continue; }
                let collateral = all_csp[tier_idx].contract.strike * 100.0 * n as f64;
                ticker_cash_used += collateral;

                let label = if tiers.len() == 1 {
                    match (stage_pos, ticker_order.len()) {
                        (_, 1) => "optimal allocation".to_string(),
                        (0, _) => format!("primary: ${:.0} ({} contracts)", collateral, n),
                        (1, _) => format!("secondary: ${:.0} → {} contract{}", collateral, n, if n == 1 { "" } else { "s" }),
                        _ => format!("tertiary: ${:.0} → {} contract{}", collateral, n, if n == 1 { "" } else { "s" }),
                    }
                } else {
                    let tier_note = if tiers.len() >= 3 {
                        let c = &all_csp[tier_idx].contract;
                        if c.delta.abs() <= 0.24 { "conservative tranche" }
                        else if c.delta.abs() >= 0.29 { "aggressive tranche" }
                        else { "moderate tranche" }
                    } else {
                        "diversified tranche"
                    };
                    format!("{}: ${:.0} ({} contract{})",
                        tier_note, collateral, n, if n == 1 { "" } else { "s" })
                };

                all_stages.push((tier_idx, n, label));
            }

            if !stage_cash.is_infinite() {
                stage_cash -= ticker_cash_used;
            }
            stage_ticker_set.insert(ticker.clone());
        }

        // ── Rationale builder ─────────────────────────────────────────────────
        let make_rationale = |entry: &CspEntry, label: Option<&str>, n: u32| -> String {
            let prefix = label.map(|l| format!("[{}] ", l)).unwrap_or_default();
            let sp = n as f64 * entry.contract.mid_price() * 100.0;
            let col = n as f64 * entry.contract.strike * 100.0;
            let qty_note = if n > 1 {
                format!(" {} contracts: total premium ${:.0}, collateral ${:.0}.", n, sp, col)
            } else { String::new() };
            format!(
                "{}Sell ${:.2} put, {} DTE (Δ{:.2}, IV {:.0}%). \
                 Mid ${:.2}/contract. Ann ROC {:.1}%. OTM {:.1}%.{} {}",
                prefix,
                entry.contract.strike,
                entry.contract.dte,
                entry.contract.delta,
                entry.contract.implied_volatility * 100.0,
                entry.contract.mid_price(),
                entry.contract.csp_return_on_capital(),
                (entry.contract.underlying_price - entry.contract.strike)
                    / entry.contract.underlying_price * 100.0,
                qty_note,
                entry.holding_note,
            )
        };

        // ── Emit staged tier allocations ──────────────────────────────────────
        let stage_keys: std::collections::HashSet<(String, u64, u32)> = all_stages
            .iter()
            .map(|(idx, _, _)| {
                let e = &all_csp[*idx];
                (e.ticker.clone(), (e.contract.strike * 100.0).round() as u64, e.contract.dte)
            })
            .collect();

        for (pos, (idx, n, label)) in all_stages.iter().enumerate() {
            let entry = &all_csp[*idx];
            let roc = entry.contract.csp_return_on_capital();
            let score = compute_quality_score(&entry.contract, roc)
                * if pos == 0 { 1.0 } else { 0.97_f64.powi(pos as i32) };
            recommendations.push(WheelRecommendation {
                ticker: entry.ticker.clone(),
                leg: WheelLeg::CashSecuredPut,
                contract: entry.contract.clone(),
                annualised_roc: roc,
                quality_score: score,
                rationale: make_rationale(entry, Some(label.as_str()), *n),
                shares_held: entry.shares_held,
                contracts_allocated: *n,
                earnings_warning: has_earnings_risk(&entry.ticker, entry.contract.dte),
            });
        }

        // ── Emit alternatives ─────────────────────────────────────────────────
        let mut alt_sorted_indices: Vec<usize> = (0..all_csp.len()).collect();
        alt_sorted_indices.sort_by(|&a, &b| {
            csp_quality(&all_csp[b].contract)
                .partial_cmp(&csp_quality(&all_csp[a].contract))
                .unwrap_or(std::cmp::Ordering::Equal)
        });

        let mut alt_per_ticker: std::collections::HashMap<String, usize> =
            std::collections::HashMap::new();
        let max_alt_per_ticker = 2usize;
        let max_alt_total = 8usize;
        let mut alt_emitted = 0usize;

        for idx in alt_sorted_indices {
            if alt_emitted >= max_alt_total { break; }
            let entry = &all_csp[idx];
            let key = (
                entry.ticker.clone(),
                (entry.contract.strike * 100.0).round() as u64,
                entry.contract.dte,
            );
            if stage_keys.contains(&key) { continue; }

            let count = alt_per_ticker.entry(entry.ticker.clone()).or_insert(0);
            if *count >= max_alt_per_ticker { continue; }

            let roc = entry.contract.csp_return_on_capital();
            let score = compute_quality_score(&entry.contract, roc) * 0.88;
            let n = if available_cash.is_finite() && available_cash > 0.0 {
                (available_cash / (entry.contract.strike * 100.0)).floor().max(1.0) as u32
            } else { 1 };
            let label = if stage_ticker_set.contains(&entry.ticker) {
                "alt strike/DTE"
            } else {
                "compare: alternative ticker"
            };

            recommendations.push(WheelRecommendation {
                ticker: entry.ticker.clone(),
                leg: WheelLeg::CashSecuredPut,
                contract: entry.contract.clone(),
                annualised_roc: roc,
                quality_score: score,
                rationale: make_rationale(entry, Some(label), n),
                shares_held: entry.shares_held,
                contracts_allocated: n,
                earnings_warning: has_earnings_risk(&entry.ticker, entry.contract.dte),
            });
            *count += 1;
            alt_emitted += 1;
        }
    }

    } // end if available_cash > 0.0

    // Sort: CCs and CSPs together by quality score.
    recommendations.sort_by(|a, b| {
        b.quality_score
            .partial_cmp(&a.quality_score)
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    recommendations
}

// ── CC tiered strike/DTE selection ────────────────────────────────────────────

/// Select up to 3 (strike, DTE) combos for covered-call diversification.
///
/// Strategy:
/// - **1 lot**: best single contract (max quality).
/// - **2 lots**: best quality + a second contract that differs in strike
///   and/or DTE from the first — with a diversity bonus so combos that vary
///   in *both* dimensions are preferred.
/// - **≥3/5 lots**: up to 3 contracts, each meaningfully different in strike
///   *or* DTE from all previously chosen contracts.
///
/// Spreading lots across strike/DTE combos reduces concentration risk:
/// different expiries avoid a single-date gamma event, and different strikes
/// balance premium capture with upside participation.
fn select_cc_tiers<'a>(
    sorted_by_quality: &[&'a OptionsContract],
    underlying: f64,
    lots: usize,
) -> Vec<&'a OptionsContract> {
    let min_strike_gap = (underlying * 0.01).max(1.0);
    let min_dte_gap: u32 = 5; // minimum DTE difference to count as a separate expiry tier
    let max_tiers = if lots >= 5 { 3 } else if lots >= 2 { 2 } else { 1 };

    if sorted_by_quality.is_empty() || max_tiers == 0 {
        return vec![];
    }

    let quality =
        |c: &OptionsContract| compute_quality_score(c, c.cc_return_on_capital());

    let mut tiers: Vec<&OptionsContract> = Vec::new();

    // First pick: highest quality contract.
    tiers.push(sorted_by_quality[0]);

    // Subsequent picks: greedy selection that rewards diversity across both
    // strike and DTE.  A diversity bonus is added on top of quality so that
    // combos differing in both dimensions outrank those differing in only one.
    while tiers.len() < max_tiers {
        let mut best: Option<(usize, f64)> = None;

        for (i, &contract) in sorted_by_quality.iter().enumerate() {
            // Skip exact duplicates (same strike + same DTE).
            let is_dup = tiers.iter().any(|t| {
                (t.strike - contract.strike).abs() < 0.01 && t.dte == contract.dte
            });
            if is_dup {
                continue;
            }

            // Must differ from every existing tier in at least one dimension.
            let distinct = tiers.iter().all(|t| {
                let diff_strike =
                    (t.strike - contract.strike).abs() >= min_strike_gap;
                let diff_dte = (t.dte as i32 - contract.dte as i32)
                    .unsigned_abs()
                    >= min_dte_gap;
                diff_strike || diff_dte
            });
            if !distinct {
                continue;
            }

            // Diversity bonus: +5 per existing tier where strike differs,
            // +5 per existing tier where DTE differs.
            let diversity: f64 = tiers
                .iter()
                .map(|t| {
                    let s = if (t.strike - contract.strike).abs() >= min_strike_gap {
                        5.0
                    } else {
                        0.0
                    };
                    let d = if (t.dte as i32 - contract.dte as i32).unsigned_abs()
                        >= min_dte_gap
                    {
                        5.0
                    } else {
                        0.0
                    };
                    s + d
                })
                .sum();

            let score = quality(contract) + diversity;
            if best.map_or(true, |(_, bs)| score > bs) {
                best = Some((i, score));
            }
        }

        match best {
            Some((idx, _)) => tiers.push(sorted_by_quality[idx]),
            None => break,
        }
    }

    // Sort tiers: DTE ascending, then strike descending within each DTE.
    tiers.sort_by(|a, b| {
        a.dte
            .cmp(&b.dte)
            .then_with(|| {
                b.strike
                    .partial_cmp(&a.strike)
                    .unwrap_or(std::cmp::Ordering::Equal)
            })
    });

    tiers
}

/// Distribute `lots` contracts across `n_tiers` tiers using a 40 / 40 / 20
/// split (or 60 / 40 for 2 tiers, or 100 % for 1 tier).
/// Each tier always gets at least 1 contract.
fn allocate_lots(lots: usize, n_tiers: usize) -> Vec<usize> {
    if n_tiers == 0 || lots == 0 {
        return vec![];
    }
    if n_tiers == 1 || lots == 1 {
        // Only 1 lot: give it to the first tier, zeros for the rest.
        let mut v = vec![0; n_tiers];
        v[0] = lots;
        return v;
    }
    if n_tiers == 2 {
        let t1 = (lots as f64 * 0.60).round() as usize;
        let t1 = t1.max(1).min(lots - 1);
        return vec![t1, lots - t1];
    }
    // 3 tiers: conservative 40 %, moderate 40 %, aggressive 20 %
    if lots == 2 {
        // Not enough for 3 tiers; split across first two.
        return vec![1, 1, 0];
    }
    let t1 = (lots as f64 * 0.40).round() as usize;
    let t1 = t1.max(1).min(lots - 2); // leave room for the other two
    let t3 = (lots as f64 * 0.20).round() as usize;
    let t3 = t3.max(1).min(lots - t1 - 1);
    let t2 = lots - t1 - t3;
    vec![t1, t2, t3]
}

// ── Scoring ───────────────────────────────────────────────────────────────────

/// Composite quality score weighing ROC, IV, delta centrality, and liquidity.
fn compute_quality_score(contract: &OptionsContract, annualised_roc: f64) -> f64 {
    // Reward higher ROC (capped at 50 pts).
    let roc_score = (annualised_roc / 60.0 * 50.0).min(50.0);

    // Reward delta near the middle of the target range (0–20 pts).
    let target_delta = 0.275_f64; // midpoint of 0.20–0.35
    let delta_deviation = (contract.delta.abs() - target_delta).abs();
    let delta_score = ((0.075 - delta_deviation) / 0.075 * 20.0).max(0.0);

    // Reward higher open interest for liquidity (0–20 pts).
    let oi_score = (contract.open_interest as f64 / 5_000.0 * 20.0).min(20.0);

    // Reward IV between 25–60 % (sweet spot for premium selling) (0–10 pts).
    let iv_score = if contract.implied_volatility >= 0.25
        && contract.implied_volatility <= 0.60
    {
        10.0
    } else if contract.implied_volatility > 0.60 {
        5.0 // high IV but elevated risk
    } else {
        2.0 // low IV, poor premium
    };

    roc_score + delta_score + oi_score + iv_score
}

// ── Rationale formatters ──────────────────────────────────────────────────────

fn format_cc_rationale(c: &OptionsContract, roc: f64, shares: u32, contracts: usize, total_lots: usize) -> String {
    let tier_label = if total_lots >= 3 {
        // Label by delta position: lower delta = more conservative (higher strike)
        if c.delta.abs() <= 0.24 {
            "Conservative tranche"
        } else if c.delta.abs() >= 0.29 {
            "Aggressive tranche"
        } else {
            "Moderate tranche"
        }
    } else if total_lots >= 2 {
        "Diversified tranche"
    } else {
        "Position"
    };

    let contracts_note = if total_lots >= 2 {
        format!(
            "{contracts} of {total_lots} contract(s) ({tier_label}). "
        )
    } else {
        String::new()
    };

    format!(
        "{contracts_note}Sell the ${:.0} call, {} DTE \
         (delta {:.2}, IV {:.0}%) against {shares} shares. \
         Mid premium: ${:.2}/contract. Annualised ROC: {:.1}%. \
         Strike is {:.1}% OTM, {}.",
        c.strike,
        c.dte,
        c.delta,
        c.implied_volatility * 100.0,
        c.mid_price(),
        roc,
        ((c.strike - c.underlying_price) / c.underlying_price) * 100.0,
        if c.delta.abs() <= 0.24 {
            "allowing more room for the stock to rise before assignment"
        } else if c.delta.abs() >= 0.29 {
            "capturing higher premium with tighter upside cap"
        } else {
            "balancing premium income with upside participation"
        }
    )
}
